### ISSUE TITLE
Does it support application/ssl-tls?

### ISSUE THREAD

**Issue by ValdikSS** [ernw/net.tcp-proxy#2]
Hi, I'm trying to use this software to intercept the program with net.tcp which upgrades connection using application/ssl-tls and it doesn't seem to work. Is it expected?

**Comment by bluec0re** [comment]
I'm sorry, but ssl-tls is not implemented yet. But should not be that complicated. I guess it's easier than the GSSAPI tunnel (from an implementation perspective). I could implement something, but can't test it.
